FROM alpine:latest

ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Install dependencies
RUN apk update \
    && apk add --no-cache \
    alpine-sdk \
    cmake \
    git \
    alsa-lib-dev \
    mesa \
    mesa-dev \
    libx11-dev \
    libxrandr-dev \
    libxi-dev \
    libxcursor-dev \
    libxinerama-dev \
    wayland-dev \
    libxkbcommon-dev \
    wayland-protocols

RUN apk add --no-cache \
    mesa-utils

# Create and change to non-root user
RUN addgroup -g $USER_GID devrunner \
    && adduser -G devrunner -u $USER_UID -D devrunner
USER devrunner
WORKDIR /home/devrunner

# Create required folders
RUN mkdir /home/devrunner/src
VOLUME /home/devrunner/src

# Default entrypoint
WORKDIR /home/devrunner/src
COPY --chown=devrunner:devrunner ./scripts/docker-run.sh /home/devrunner/
ENTRYPOINT ["/home/devrunner/docker-run.sh"]

